name: CI

on:
  pull_request:
    branches:
      - main
      - dev-main

  workflow_dispatch:
    inputs:
      branch_to_test:
        description: 'Branch or tag to run test'
        required: true
        default: 'dev_main'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Pull Request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: Checkout Repository (Workflow Dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_to_test }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.5'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint
